# Generated by Django 5.2.11 on 2026-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saletransaction',
            new_name='sales_salet_created_7a0b54_idx',
            old_name='sales_sale_created_32e9ec_idx',
        ),
        migrations.RenameIndex(
            model_name='saletransaction',
            new_name='sales_salet_org_id_7eb303_idx',
            old_name='sales_sale_org_id_2f56fb_idx',
        ),
    ]
