services:
  db:
    ports: []
    restart: unless-stopped

  redis:
    ports: []
    restart: unless-stopped

  web:
    command:
      [
        "gunicorn",
        "config.wsgi:application",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "3",
        "--timeout",
        "120",
      ]
    volumes:
      - photoharu_media:/app/src/media
    restart: unless-stopped

  celery_worker:
    restart: unless-stopped

  celery_beat:
    restart: unless-stopped
