# Generated by Django 5.2.11 on 2026-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configprofile',
            new_name='configs_con_scope_778492_idx',
            old_name='configs_con_scope_088f75_idx',
        ),
    ]
