from urllib.parse import urlencode

from django.urls import reverse


SUPPORTED_DASHBOARD_LANGS = ("ko", "en")
DEFAULT_DASHBOARD_CURRENCY_UNIT = "KRW"
MAX_DASHBOARD_CURRENCY_UNIT_LENGTH = 12

_UI_TEXT = {
    "ko": {
        "base": {
            "app_title": "Viorafilm Dashboard",
            "subtitle": "Kiosk Control Center",
            "page_title": "운영 대시보드",
            "menu_button": "메뉴",
            "language": "언어",
            "lang_ko": "한국어",
            "lang_en": "English",
            "menu_index": "매출 현황",
            "menu_devices": "장치 관리",
            "menu_ops": "관측성",
            "menu_billing": "수금 관리",
            "menu_sales": "매출 관리",
            "menu_coupons": "쿠폰 관리",
            "menu_photos": "사진 관리",
            "change_password": "비밀번호 변경",
            "logout": "로그아웃",
            "currency_unit": "화폐 단위",
            "currency_apply": "적용",
            "timezone_active": "기준 시간대",
            "timezone_scope": "적용 범위",
            "timezone_name": "시간대",
            "timezone_apply": "저장",
        },
        "common": {
            "organization": "조직",
            "all_organizations": "전체 조직",
            "branch": "지점",
            "all_branches": "전체 지점",
            "apply_filters": "필터 적용",
            "reset_filters": "필터 초기화",
            "generated_at": "생성 시각",
            "created_at": "생성 시간",
            "time": "시간",
            "device": "장치",
            "token": "토큰",
            "status": "상태",
            "preview": "미리보기",
            "download": "다운로드",
            "share": "공유",
            "view_count": "조회수",
            "open": "열기",
            "active": "활성",
            "expired": "만료",
            "online_badge": "온라인",
            "offline_badge": "오프라인",
            "ok": "정상",
            "issue": "오류",
            "viewer_read_only": "VIEWER 권한은 읽기 전용입니다.",
            "billing_admin_only": "수금 관리는 admin 계정만 사용할 수 있습니다.",
        },
        "timezone": {
            "scope_global": "전역",
            "scope_org": "조직",
            "scope_branch": "지점",
            "invalid_name": "유효한 시간대를 선택하세요.",
            "missing_org": "적용할 조직을 찾을 수 없습니다.",
            "missing_branch": "적용할 지점을 찾을 수 없습니다.",
            "unsupported_scope": "지원하지 않는 시간대 범위입니다.",
            "saved_global": "전역 기준 시간이 {timezone}로 저장되었습니다.",
            "saved_org": "{org} 조직 기준 시간이 {timezone}로 저장되었습니다.",
            "saved_branch": "{org}/{branch} 지점 기준 시간이 {timezone}로 저장되었습니다.",
        },
        "login": {
            "page_title": "로그인",
            "subtitle": "관리자 로그인",
            "invalid_credentials": "아이디 또는 비밀번호가 올바르지 않습니다.",
            "username": "아이디",
            "password": "비밀번호",
            "submit": "로그인",
        },
        "index": {
            "today_total": "오늘 매출",
            "month_total": "이번 달 매출",
            "sales_count": "총 거래 건수",
            "view_devices": "장치 상태 보기",
            "view_ops": "관측성 보기",
            "view_billing": "수금 관리 보기",
            "view_sales": "매출 내역 보기",
            "view_coupons": "쿠폰 관리 보기",
            "view_photos": "사진 관리 보기",
        },
        "devices": {
            "title": "장치 관리",
            "auto_refresh_badge_on": "AUTO 5s",
            "auto_refresh_badge_off": "AUTO OFF",
            "auto_refresh_on": "자동 새로고침 ON",
            "auto_refresh_off": "자동 새로고침 OFF",
            "refresh_now": "지금 새로고침",
            "show_all": "전체 보기",
            "show_locked_only": "잠금 장치만 보기",
            "locked_only_badge": "잠금 장치만",
            "email_settings_title": "이메일 알림 설정",
            "email_settings_help": "장치 오프라인, 카메라, 프린터, 인터넷 이상 알림을 받을 이메일을 입력하세요. 여러 주소는 쉼표(,)로 구분합니다.",
            "email_placeholder": "example1@viorafilm.com, example2@viorafilm.com",
            "save_emails": "이메일 저장",
            "send_test_email": "테스트 메일 발송",
            "viewer_email_read_only": "VIEWER 권한은 이메일 알림 설정을 수정할 수 없습니다.",
            "device_status_title": "장치 상태",
            "table_org_branch": "조직/지점",
            "table_last_seen": "마지막 통신",
            "table_online": "온라인",
            "table_internet": "인터넷",
            "table_camera": "카메라",
            "table_printer": "프린터",
            "table_film_remaining": "필름 잔량",
            "table_offline_guard": "오프라인 가드",
            "table_offline_remaining": "오프라인 남은시간",
            "table_lock": "잠금",
            "table_lock_reason": "잠금 사유",
            "table_last_online_auth": "마지막 온라인 인증",
            "table_mode_access": "모드 권한",
            "table_action": "액션",
            "offline_state_notice": "오프라인 장비 상태는 마지막 통신 기준입니다. 서버 잠금 해제는 바로 저장되지만, 장비 프로그램이 다시 켜져 서버에 연결될 때 반영됩니다.",
            "film_estimate_prefix": "예상",
            "film_unit": "장",
            "offline_guard_enabled": "활성",
            "offline_guard_off": "비활성",
            "offline_overdue_prefix": "초과",
            "lock_server": "서버 잠금",
            "lock_offline": "오프라인 잠금",
            "lock_unlocked": "정상",
            "lock_pending_delivery": "서버 해제됨",
            "lock_pending_delivery_help": "앱 시작 후 재인증이 전달되면 로컬 오프라인 잠금이 해제됩니다.",
            "celebrity_on": "연예인 ON",
            "celebrity_off": "연예인 OFF",
            "ai_on": "AI ON",
            "ai_off": "AI OFF",
            "mode_permissions_hint": "Admin 페이지에서 변경",
            "unlock": "잠금 해제",
            "lock": "잠금",
            "lock_reason_placeholder": "사유 (선택)",
            "read_only": "읽기 전용",
            "empty": "표시할 장치가 없습니다.",
            "save_alert_emails_success": "알림 이메일 {count}개를 저장했습니다.",
            "save_alert_emails_first": "먼저 알림 이메일을 저장하세요.",
            "console_email_backend": "현재 이메일 백엔드가 콘솔 모드입니다. 실제 메일 발송을 위해 SMTP 설정을 먼저 입력하세요.",
            "test_email_subject": "[Viorafilm] 테스트 알림 메일",
            "test_email_body_intro": "이 메일은 Viorafilm 대시보드에서 발송한 테스트 알림입니다.",
            "test_email_body_time": "시간",
            "test_email_body_user": "발신 사용자",
            "test_email_success": "테스트 메일 발송 완료: 성공 {sent}, 실패 {failed}",
            "test_email_failure": "테스트 메일 발송 실패: 성공 {sent}, 실패 {failed}",
            "invalid_device_id": "잘못된 장치 ID 입니다.",
            "device_not_found": "해당 장치를 찾을 수 없습니다.",
            "device_locked": "장치 잠금 처리 완료: {device}",
            "device_unlocked": "장치 잠금 해제 완료: {device}",
            "offline_unlock_sent": "오프라인 가드 재인증을 전송했습니다: {device}",
            "offline_unlock_pending": "재인증 대기",
            "offline_unlock_pending_help": "앱 실행 후 자동 반영",
            "offline_unlock_pending_conflict": "다른 원격 액션이 대기 중이라 오프라인 가드 재인증은 나중에 적용됩니다: {device}",
            "remote_credit": "코인 활성화",
            "remote_credit_disable": "코인 비활성화",
            "remote_credit_pending": "활성화됨",
            "remote_credit_unavailable": "다음 결제화면에서 적용",
            "remote_credit_sent": "원격 코인을 전송했습니다: {device}",
            "remote_credit_cleared": "원격 코인을 비활성화했습니다: {device}",
            "remote_credit_already_pending": "이미 대기 중인 원격 코인이 있습니다: {device}",
            "log_view": "로그",
            "log_title": "장치 로그",
            "log_notice": "이 화면은 키오스크 앱이 마지막 heartbeat에서 보고한 로그 tail입니다. 앱이 꺼져 있거나 네트워크가 끊기면 갱신되지 않습니다.",
            "log_filename": "로그 파일",
            "log_updated_at": "로그 갱신 시각",
            "log_empty": "보고된 로그가 없습니다.",
        },
        "ops": {
            "title": "관측성",
            "summary_device_count": "장치 수",
            "summary_online_count": "온라인 장치",
            "summary_locked_count": "잠금 장치",
            "summary_share_queue_device_count": "업로드 대기 장치",
            "summary_heartbeat_1h": "Heartbeat 1시간",
            "summary_heartbeat_24h": "Heartbeat 24시간",
            "summary_share_24h": "공유 세션 24시간",
            "summary_share_finalized_24h": "완료 공유 24시간",
            "summary_upload_24h": "업로드 파일 24시간",
            "summary_sales_24h": "매출 전송 24시간",
            "device_observability_title": "장치 관측성",
            "table_pending_upload": "대기 업로드",
            "table_pending_sales": "대기 매출",
            "table_pending_heartbeat": "대기 heartbeat",
            "table_total_queue": "총 큐",
            "recent_shares_title": "최근 공유 세션",
            "table_file_keys": "파일 키",
            "table_upload_count": "업로드 파일 수",
            "empty_devices": "표시할 장치가 없습니다.",
            "empty_shares": "최근 공유 세션이 없습니다.",
            "lock_locked": "LOCKED",
            "lock_normal": "정상",
        },
        "billing": {
            "title": "수금 관리",
            "month_summary_prefix": "기준 월",
            "period_prefix": "집계 기간",
            "live_month_suffix": "(현재 월 실시간 누적)",
            "organization": "조직",
            "all_organizations": "전체 조직",
            "branch": "지점",
            "all_branches": "전체 지점",
            "billing_month": "정산 월",
            "apply_filters": "필터 적용",
            "reset_filters": "필터 초기화",
            "previous_month": "이전 달",
            "next_month": "다음 달",
            "branch_count": "브랜치 수",
            "device_count": "활성 장치 수",
            "server_fee_total": "장치 서버비",
            "ai_extra_total": "AI 추가 청구",
            "requested_total": "요청 금액 합계",
            "paid_count": "수금 완료 브랜치",
            "info_prefix": "장치 서버비는 현재 활성 장치 기준으로 1대당",
            "info_suffix": "입니다. AI 추가 청구액은 해당 월 AI 사용량 기준 예상액입니다.",
            "table_org": "조직",
            "table_branch": "지점",
            "table_active_devices": "활성 장치",
            "table_server_fee": "장치 서버비",
            "table_ai_usage": "AI 거래/이미지",
            "table_ai_extra": "AI 추가 청구",
            "table_requested": "요청 금액",
            "table_status": "상태",
            "table_paid_at": "수금 시각",
            "table_note": "메모",
            "table_action": "처리",
            "status_paid": "수금 완료",
            "status_pending": "미수금",
            "placeholder_note": "메모",
            "mark_pending": "미수금",
            "mark_paid": "수금 완료",
            "read_only": "읽기 전용",
            "empty": "표시할 정산 대상이 없습니다.",
            "message_paid": "{branch} {month} 수금 완료로 표시했습니다.",
            "message_pending": "{branch} {month} 미수금으로 표시했습니다.",
            "message_missing_branch": "수금 상태를 변경할 지점을 찾지 못했습니다.",
            "message_unsupported": "지원하지 않는 수금 처리 요청입니다.",
        },
        "sales": {
            "title": "매출 관리",
            "export_csv": "엑셀 다운로드(CSV)",
            "per_page": "페이지당 표시",
            "payment_filter": "결제수단",
            "payment_filter_all": "전체",
            "payment_filter_cash": "현금",
            "payment_filter_card": "카드",
            "payment_filter_coupon": "쿠폰",
            "payment_filter_coupon_cash": "쿠폰+현금",
            "payment_filter_coupon_card": "쿠폰+카드",
            "period": "기간",
            "period_week": "최근 7일",
            "period_month": "이번 달",
            "period_custom": "특정 기간",
            "billing_month": "AI 청구 월",
            "start_date": "시작일",
            "end_date": "종료일",
            "summary_total_amount": "기간 매출 합계",
            "summary_total_count": "기간 거래 건수",
            "mode_normal_title": "일반 모드",
            "mode_ai_title": "AI 모드",
            "mode_celebrity_title": "유명인 합성 모드",
            "mode_count_label": "건수",
            "ai_billing_title": "AI 월별 청구 예상액 (브랜치별)",
            "billing_month_prefix": "기준 월",
            "billing_period_prefix": "집계 기간",
            "billing_live_suffix": "(현재 월 실시간 누적)",
            "ai_sales_count": "AI 거래 건수",
            "ai_generated_images": "AI 생성 이미지",
            "ai_estimated_total": "월 청구 예상 합계",
            "table_org": "조직",
            "table_branch_code": "지점코드",
            "table_branch_name": "지점명",
            "table_ai_sales": "AI 거래",
            "table_ai_images": "AI 이미지",
            "table_estimated_charge": "청구 예상액",
            "ai_empty": "해당 월 AI 사용 내역이 없습니다.",
            "chart_title": "매출 그래프",
            "table_time": "시간",
            "table_session": "세션",
            "table_layout": "레이아웃",
            "table_mode": "모드",
            "table_total": "총액",
            "table_payment_method": "결제수단",
            "table_cash": "현금",
            "table_card": "카드",
            "table_coupon": "쿠폰",
            "table_coupon_code": "쿠폰코드",
            "table_cancel_status": "취소상태",
            "table_actions": "동작",
            "mode_normal": "일반",
            "mode_ai": "AI",
            "mode_celebrity": "유명인 합성",
            "empty": "매출 데이터가 없습니다.",
            "chart_dataset_revenue": "매출 ({currency})",
            "chart_dataset_transactions": "거래 건수",
            "chart_axis_revenue": "매출({currency})",
            "chart_axis_transactions": "거래 건수",
            "cancel_button": "결제취소",
            "cancel_success_badge": "취소완료",
            "cancel_queued_badge": "취소대기",
            "cancel_error_badge": "취소실패",
            "cancel_pending_note": "키오스크 처리 대기중",
            "cancel_done_note": "취소 처리됨",
            "cancel_device_busy_note": "다른 원격 작업 대기중",
            "cancel_not_supported": "이 거래는 대시보드 원격 취소를 지원하지 않습니다.",
            "cancel_sale_missing": "취소할 거래를 찾지 못했습니다.",
            "cancel_pending_other": "해당 키오스크에 다른 원격 작업이 이미 대기 중입니다: {device}",
            "cancel_queued": "원격 결제 취소를 요청했습니다. 세션={session} 장치={device}",
            "previous": "이전",
            "next": "다음",
            "pagination_aria": "매출 페이지 이동",
        },
        "photos": {
            "title": "사진 관리",
            "token_search": "Token 검색",
            "token_search_placeholder": "token 검색",
            "search_results": "검색 결과",
            "recent_7days": "최근 7일 기준",
            "table_created_at": "생성 시간",
            "table_token": "Token",
            "table_status": "상태",
            "table_expires": "만료",
            "table_views": "조회수",
            "table_preview": "미리보기",
            "table_download": "다운로드",
            "table_share": "공유",
            "status_active": "ACTIVE",
            "status_expired": "EXPIRED",
            "download_print": "print",
            "download_frame": "frame",
            "download_gif": "gif",
            "download_video": "video",
            "download_original": "original {number}",
            "share_open": "open",
            "empty": "공유 세션이 없습니다.",
        },
        "coupons": {
            "title": "쿠폰 관리",
            "export_csv": "엑셀 다운로드(CSV)",
            "per_page": "페이지당 표시",
            "issue_title": "쿠폰 일괄 발행",
            "capacity_global": "전체 한도 {max}장 / 현재 {count}장 / 남은 {remaining}장",
            "capacity_scoped": "현재 범위 쿠폰 {count}장",
            "capacity_per_issue": "1회 최대 {count}장",
            "org_none": "(없음)",
            "branch_none": "(없음)",
            "amount": "금액",
            "count": "수량",
            "expires_in": "유효기간",
            "expires_1d": "1일",
            "expires_1w": "1주일",
            "expires_1m": "1달",
            "expires_1y": "1년",
            "batch_name": "배치명",
            "batch_name_placeholder": "선택",
            "issue_submit": "발행",
            "select_all_on_page": "현재 페이지 전체선택",
            "recover_missing_usage": "누락 사용 복구",
            "delete_selected": "선택 삭제",
            "delete_used": "사용완료 삭제",
            "delete_expired": "만료 삭제",
            "viewer_read_only": "VIEWER 권한은 읽기 전용입니다.",
            "select_all_aria": "현재 페이지 쿠폰 전체선택",
            "table_code": "코드",
            "table_amount": "금액",
            "table_expires": "만료",
            "table_status": "상태",
            "table_used_device": "사용 장치",
            "table_used_session": "사용 세션",
            "table_created_at": "생성 시간",
            "empty": "쿠폰 데이터가 없습니다.",
            "previous": "이전",
            "next": "다음",
            "pagination_aria": "쿠폰 페이지 이동",
            "invalid_issue_params": "금액, 수량, 유효기간은 0보다 커야 합니다.",
            "issue_count_min": "발행 수량은 1개 이상이어야 합니다.",
            "issue_count_max": "1회 발행 최대 수량은 {max}개입니다.",
            "issue_capacity_exceeded": "전체 쿠폰 발행 한도를 초과했습니다. 시스템 관리 한도를 확인해 주세요.",
            "issue_success": "쿠폰 묶음 발행 완료 (Batch #{batch_id})",
            "delete_selected_success": "선택한 쿠폰을 삭제했습니다: {count}",
            "delete_used_success": "사용 완료 쿠폰을 삭제했습니다: {count}",
            "delete_expired_success": "만료 쿠폰을 삭제했습니다: {count}",
            "recover_missing_usage_success": "누락 사용 복구 완료 (검사 {scanned} / 연결 {linked_sales} / 사용처리 {coupon_marked_used} / 코드없음 {skipped_no_code} / 미존재 {skipped_not_found} / 충돌 {skipped_conflict})",
        },
    },
    "en": {
        "base": {
            "app_title": "Viorafilm Dashboard",
            "subtitle": "Kiosk Operations Console",
            "page_title": "Operations Dashboard",
            "menu_button": "Menu",
            "language": "Language",
            "lang_ko": "Korean",
            "lang_en": "English",
            "menu_index": "Overview",
            "menu_devices": "Devices",
            "menu_ops": "Monitoring",
            "menu_billing": "Billing",
            "menu_sales": "Sales",
            "menu_coupons": "Coupons",
            "menu_photos": "Photos",
            "change_password": "Change Password",
            "logout": "Sign Out",
            "currency_unit": "Currency",
            "currency_apply": "Apply",
            "timezone_active": "Display Timezone",
            "timezone_scope": "Apply To",
            "timezone_name": "Timezone",
            "timezone_apply": "Save",
        },
        "common": {
            "organization": "Organization",
            "all_organizations": "All Organizations",
            "branch": "Branch",
            "all_branches": "All Branches",
            "apply_filters": "Apply Filters",
            "reset_filters": "Reset Filters",
            "generated_at": "Generated at",
            "created_at": "Created At",
            "time": "Time",
            "device": "Device",
            "token": "Token",
            "status": "Status",
            "preview": "Preview",
            "download": "Download",
            "share": "Share",
            "view_count": "Views",
            "open": "Open",
            "active": "Active",
            "expired": "Expired",
            "online_badge": "ONLINE",
            "offline_badge": "OFFLINE",
            "ok": "OK",
            "issue": "Issue",
            "viewer_read_only": "Viewer accounts are read-only.",
            "billing_admin_only": "Billing is available only to the admin account.",
        },
        "timezone": {
            "scope_global": "Global",
            "scope_org": "Organization",
            "scope_branch": "Branch",
            "invalid_name": "Choose a valid timezone.",
            "missing_org": "Could not find an organization for this change.",
            "missing_branch": "Could not find a branch for this change.",
            "unsupported_scope": "Unsupported timezone scope.",
            "saved_global": "Saved the global display timezone as {timezone}.",
            "saved_org": "Saved the display timezone for organization {org} as {timezone}.",
            "saved_branch": "Saved the display timezone for branch {org}/{branch} as {timezone}.",
        },
        "login": {
            "page_title": "Sign In",
            "subtitle": "Administrator Sign In",
            "invalid_credentials": "Invalid username or password.",
            "username": "Username",
            "password": "Password",
            "submit": "Sign In",
        },
        "index": {
            "today_total": "Today's Sales",
            "month_total": "This Month's Sales",
            "sales_count": "Total Transactions",
            "view_devices": "View Devices",
            "view_ops": "View Monitoring",
            "view_billing": "View Billing",
            "view_sales": "View Sales",
            "view_coupons": "View Coupons",
            "view_photos": "View Photos",
        },
        "devices": {
            "title": "Device Management",
            "auto_refresh_badge_on": "AUTO 5s",
            "auto_refresh_badge_off": "AUTO OFF",
            "auto_refresh_on": "Auto Refresh On",
            "auto_refresh_off": "Auto Refresh Off",
            "refresh_now": "Refresh Now",
            "show_all": "Show All",
            "show_locked_only": "Show Locked Only",
            "locked_only_badge": "Locked Only",
            "email_settings_title": "Email Alerts",
            "email_settings_help": "Enter the email addresses that should receive offline, camera, printer, and internet alerts. Separate multiple addresses with commas.",
            "email_placeholder": "ops@viorafilm.com, support@viorafilm.com",
            "save_emails": "Save Emails",
            "send_test_email": "Send Test Email",
            "viewer_email_read_only": "Viewer accounts cannot change email alert settings.",
            "device_status_title": "Device Status",
            "table_org_branch": "Organization / Branch",
            "table_last_seen": "Last Seen",
            "table_online": "Online",
            "table_internet": "Internet",
            "table_camera": "Camera",
            "table_printer": "Printer",
            "table_film_remaining": "Film Remaining",
            "table_offline_guard": "Offline Guard",
            "table_offline_remaining": "Grace Remaining",
            "table_lock": "Lock",
            "table_lock_reason": "Lock Reason",
            "table_last_online_auth": "Last Online Auth",
            "table_mode_access": "Mode Access",
            "table_action": "Action",
            "offline_state_notice": "Offline devices show their last reported state. Server unlock is saved immediately, but it is only applied after the kiosk app starts and reconnects to the server.",
            "film_estimate_prefix": "Est.",
            "film_unit": "sheets",
            "offline_guard_enabled": "Enabled",
            "offline_guard_off": "Off",
            "offline_overdue_prefix": "Overdue",
            "lock_server": "Server Lock",
            "lock_offline": "Offline Lock",
            "lock_unlocked": "Unlocked",
            "lock_pending_delivery": "Server Unlocked",
            "lock_pending_delivery_help": "The local offline lock will clear after the kiosk app starts and receives the refresh action.",
            "celebrity_on": "Celebrity On",
            "celebrity_off": "Celebrity Off",
            "ai_on": "AI On",
            "ai_off": "AI Off",
            "mode_permissions_hint": "Manage permissions in the Admin panel.",
            "unlock": "Unlock",
            "lock": "Lock",
            "lock_reason_placeholder": "Reason (optional)",
            "read_only": "Read-only",
            "empty": "No devices found.",
            "save_alert_emails_success": "Saved {count} alert email addresses.",
            "save_alert_emails_first": "Save at least one alert email address first.",
            "console_email_backend": "The email backend is set to console mode. Configure SMTP before sending real email.",
            "test_email_subject": "[Viorafilm] Test Alert Email",
            "test_email_body_intro": "This is a test alert sent from the Viorafilm dashboard.",
            "test_email_body_time": "Time",
            "test_email_body_user": "Triggered by",
            "test_email_success": "Test email sent: {sent} succeeded, {failed} failed.",
            "test_email_failure": "Test email failed: {sent} succeeded, {failed} failed.",
            "invalid_device_id": "Invalid device ID.",
            "device_not_found": "Device not found.",
            "device_locked": "Device locked: {device}",
            "device_unlocked": "Device unlocked: {device}",
            "offline_unlock_sent": "Offline guard refresh queued: {device}",
            "offline_unlock_pending": "Refresh Pending",
            "offline_unlock_pending_help": "Applies automatically after the app starts",
            "offline_unlock_pending_conflict": "Another remote action is already pending, so offline guard refresh will be delayed: {device}",
            "remote_credit": "Enable Credit",
            "remote_credit_disable": "Disable Credit",
            "remote_credit_pending": "Enabled",
            "remote_credit_unavailable": "Applies On Next Payment Screen",
            "remote_credit_sent": "Remote credit sent: {device}",
            "remote_credit_cleared": "Remote credit disabled: {device}",
            "remote_credit_already_pending": "Remote credit already pending: {device}",
            "log_view": "Logs",
            "log_title": "Device Logs",
            "log_notice": "This page shows the log tail reported by the kiosk app in its latest heartbeat. It does not update while the app is offline or stopped.",
            "log_filename": "Log File",
            "log_updated_at": "Log Updated At",
            "log_empty": "No reported logs are available.",
        },
        "ops": {
            "title": "Operations Monitoring",
            "summary_device_count": "Devices",
            "summary_online_count": "Online Devices",
            "summary_locked_count": "Locked Devices",
            "summary_share_queue_device_count": "Devices with Pending Uploads",
            "summary_heartbeat_1h": "Heartbeats (1h)",
            "summary_heartbeat_24h": "Heartbeats (24h)",
            "summary_share_24h": "Share Sessions (24h)",
            "summary_share_finalized_24h": "Completed Shares (24h)",
            "summary_upload_24h": "Uploaded Files (24h)",
            "summary_sales_24h": "Sales Synced (24h)",
            "device_observability_title": "Device Health",
            "table_pending_upload": "Pending Uploads",
            "table_pending_sales": "Pending Sales",
            "table_pending_heartbeat": "Pending Heartbeats",
            "table_total_queue": "Total Queue",
            "recent_shares_title": "Recent Share Sessions",
            "table_file_keys": "File Keys",
            "table_upload_count": "Uploaded Files",
            "empty_devices": "No devices to display.",
            "empty_shares": "No recent share sessions.",
            "lock_locked": "Locked",
            "lock_normal": "Normal",
        },
        "billing": {
            "title": "Billing",
            "month_summary_prefix": "Billing Month",
            "period_prefix": "Period",
            "live_month_suffix": "(month-to-date)",
            "organization": "Organization",
            "all_organizations": "All Organizations",
            "branch": "Branch",
            "all_branches": "All Branches",
            "billing_month": "Billing Month",
            "apply_filters": "Apply Filters",
            "reset_filters": "Reset Filters",
            "previous_month": "Previous Month",
            "next_month": "Next Month",
            "branch_count": "Branches",
            "device_count": "Active Devices",
            "server_fee_total": "Device Server Fee",
            "ai_extra_total": "AI Surcharge",
            "requested_total": "Requested Total",
            "paid_count": "Paid Branches",
            "info_prefix": "Per-device monthly server fee is",
            "info_suffix": ". AI surcharge is estimated from monthly AI usage.",
            "table_org": "Organization",
            "table_branch": "Branch",
            "table_active_devices": "Active Devices",
            "table_server_fee": "Device Fee",
            "table_ai_usage": "AI Sales / Images",
            "table_ai_extra": "AI Surcharge",
            "table_requested": "Requested Total",
            "table_status": "Status",
            "table_paid_at": "Paid At",
            "table_note": "Note",
            "table_action": "Action",
            "status_paid": "Paid",
            "status_pending": "Pending",
            "placeholder_note": "Note",
            "mark_pending": "Mark Pending",
            "mark_paid": "Mark Paid",
            "read_only": "Read-only",
            "empty": "No billing targets found.",
            "message_paid": "Marked {branch} {month} as paid.",
            "message_pending": "Marked {branch} {month} as pending.",
            "message_missing_branch": "Could not find the branch to update.",
            "message_unsupported": "Unsupported billing action.",
        },
        "sales": {
            "title": "Sales Analytics",
            "export_csv": "Export CSV",
            "per_page": "Rows per Page",
            "payment_filter": "Payment",
            "payment_filter_all": "All",
            "payment_filter_cash": "Cash",
            "payment_filter_card": "Card",
            "payment_filter_coupon": "Coupon",
            "payment_filter_coupon_cash": "Coupon + Cash",
            "payment_filter_coupon_card": "Coupon + Card",
            "period": "Period",
            "period_week": "Last 7 Days",
            "period_month": "This Month",
            "period_custom": "Custom Range",
            "billing_month": "AI Billing Month",
            "start_date": "Start Date",
            "end_date": "End Date",
            "summary_total_amount": "Revenue in Range",
            "summary_total_count": "Transactions in Range",
            "mode_normal_title": "Standard Mode",
            "mode_ai_title": "AI Mode",
            "mode_celebrity_title": "Celebrity Composite Mode",
            "mode_count_label": "Transactions",
            "ai_billing_title": "Estimated Monthly AI Charges by Branch",
            "billing_month_prefix": "Billing Month",
            "billing_period_prefix": "Coverage",
            "billing_live_suffix": "(month-to-date)",
            "ai_sales_count": "AI Transactions",
            "ai_generated_images": "AI Images Generated",
            "ai_estimated_total": "Estimated Monthly Total",
            "table_org": "Organization",
            "table_branch_code": "Branch Code",
            "table_branch_name": "Branch Name",
            "table_ai_sales": "AI Sales",
            "table_ai_images": "AI Images",
            "table_estimated_charge": "Estimated Charge",
            "ai_empty": "No AI activity found for this billing month.",
            "chart_title": "Sales Trend",
            "table_time": "Time",
            "table_session": "Session",
            "table_layout": "Layout",
            "table_mode": "Mode",
            "table_total": "Total",
            "table_payment_method": "Payment Method",
            "table_cash": "Cash",
            "table_card": "Card",
            "table_coupon": "Coupon",
            "table_coupon_code": "Coupon Code",
            "table_cancel_status": "Cancel Status",
            "table_actions": "Actions",
            "mode_normal": "Standard",
            "mode_ai": "AI",
            "mode_celebrity": "Celebrity Composite",
            "empty": "No sales found for the selected range.",
            "chart_dataset_revenue": "Revenue ({currency})",
            "chart_dataset_transactions": "Transactions",
            "chart_axis_revenue": "Revenue ({currency})",
            "chart_axis_transactions": "Transactions",
            "cancel_button": "Cancel Payment",
            "cancel_success_badge": "Cancelled",
            "cancel_queued_badge": "Queued",
            "cancel_error_badge": "Failed",
            "cancel_pending_note": "Waiting for kiosk",
            "cancel_done_note": "Cancellation complete",
            "cancel_device_busy_note": "Another remote action is pending",
            "cancel_not_supported": "This sale does not support remote dashboard cancellation.",
            "cancel_sale_missing": "The selected sale could not be found.",
            "cancel_pending_other": "Another remote action is already pending for this kiosk: {device}",
            "cancel_queued": "Remote payment cancellation queued. Session={session} Device={device}",
            "previous": "Previous",
            "next": "Next",
            "pagination_aria": "Sales pagination",
        },
        "photos": {
            "title": "Photo Sharing",
            "token_search": "Search Token",
            "token_search_placeholder": "Search by token",
            "search_results": "Showing search results",
            "recent_7days": "Showing sessions from the last 7 days",
            "table_created_at": "Created At",
            "table_token": "Token",
            "table_status": "Status",
            "table_expires": "Expires At",
            "table_views": "Views",
            "table_preview": "Preview",
            "table_download": "Download",
            "table_share": "Share",
            "status_active": "Active",
            "status_expired": "Expired",
            "download_print": "Print",
            "download_frame": "Frame",
            "download_gif": "GIF",
            "download_video": "Video",
            "download_original": "Original {number}",
            "share_open": "Open",
            "empty": "No share sessions found.",
        },
        "coupons": {
            "title": "Coupon Operations",
            "export_csv": "Export CSV",
            "per_page": "Rows per Page",
            "issue_title": "Issue Coupon Batch",
            "capacity_global": "Global capacity {max} / in use {count} / remaining {remaining}",
            "capacity_scoped": "Coupons in the current scope: {count}",
            "capacity_per_issue": "Maximum per batch: {count}",
            "org_none": "(none)",
            "branch_none": "(none)",
            "amount": "Amount",
            "count": "Quantity",
            "expires_in": "Validity",
            "expires_1d": "1 day",
            "expires_1w": "1 week",
            "expires_1m": "1 month",
            "expires_1y": "1 year",
            "batch_name": "Batch Name",
            "batch_name_placeholder": "Optional",
            "issue_submit": "Issue Coupons",
            "select_all_on_page": "Select all on this page",
            "recover_missing_usage": "Recover Missing Usage",
            "delete_selected": "Delete Selected",
            "delete_used": "Delete Used",
            "delete_expired": "Delete Expired",
            "viewer_read_only": "Viewer accounts are read-only.",
            "select_all_aria": "Select all coupons on this page",
            "table_code": "Code",
            "table_amount": "Amount",
            "table_expires": "Expires At",
            "table_status": "Status",
            "table_used_device": "Used Device",
            "table_used_session": "Used Session",
            "table_created_at": "Created At",
            "empty": "No coupons found.",
            "previous": "Previous",
            "next": "Next",
            "pagination_aria": "Coupon pagination",
            "invalid_issue_params": "Amount, quantity, and validity must all be greater than zero.",
            "issue_count_min": "You must issue at least one coupon.",
            "issue_count_max": "You can issue up to {max} coupons in a single batch.",
            "issue_capacity_exceeded": "Global coupon capacity has been reached. Review the system limit before issuing more coupons.",
            "issue_success": "Issued coupon batch (Batch #{batch_id}).",
            "delete_selected_success": "Deleted selected coupons: {count}",
            "delete_used_success": "Deleted used coupons: {count}",
            "delete_expired_success": "Deleted expired coupons: {count}",
            "recover_missing_usage_success": "Recovered missing coupon usage (scanned {scanned} / linked {linked_sales} / marked used {coupon_marked_used} / no code {skipped_no_code} / not found {skipped_not_found} / conflicts {skipped_conflict}).",
        },
    },
}


def resolve_dashboard_lang(request):
    requested = str(request.GET.get("lang") or request.POST.get("lang") or "").strip().lower()
    session_lang = str(getattr(request, "session", {}).get("dashboard_lang", "") or "").strip().lower()
    lang = requested if requested in SUPPORTED_DASHBOARD_LANGS else session_lang
    if lang not in SUPPORTED_DASHBOARD_LANGS:
        lang = "ko"
    if hasattr(request, "session"):
        request.session["dashboard_lang"] = lang
    return lang


def normalize_dashboard_currency_unit(value):
    cleaned = " ".join(str(value or "").strip().split())
    if not cleaned:
        return DEFAULT_DASHBOARD_CURRENCY_UNIT
    return cleaned[:MAX_DASHBOARD_CURRENCY_UNIT_LENGTH]


def resolve_dashboard_currency_unit(request):
    requested = request.POST.get("currency_unit") if getattr(request, "method", "GET") == "POST" else None
    if requested is None:
        requested = request.GET.get("currency_unit")
    session_currency = str(getattr(request, "session", {}).get("dashboard_currency_unit", "") or "").strip()
    currency = normalize_dashboard_currency_unit(requested if requested not in (None, "") else session_currency)
    if hasattr(request, "session"):
        request.session["dashboard_currency_unit"] = currency
    return currency


def can_manage_billing(user):
    return bool(getattr(user, "is_authenticated", False)) and str(getattr(user, "username", "")).strip().lower() == "admin"


def get_dashboard_text(lang):
    return _UI_TEXT.get(lang, _UI_TEXT["ko"])


def resolve_dashboard_text(request):
    return get_dashboard_text(resolve_dashboard_lang(request))


def build_query_string(params):
    clean = {}
    for key, value in params.items():
        if value in (None, ""):
            continue
        clean[key] = value
    if not clean:
        return ""
    return urlencode(clean)


def build_path_with_query(path, params):
    query = build_query_string(params)
    return f"{path}?{query}" if query else path


def build_dashboard_ui(request):
    lang = resolve_dashboard_lang(request)
    currency_unit = resolve_dashboard_currency_unit(request)
    text = get_dashboard_text(lang)
    base = text["base"]
    current_params = request.GET.copy()
    switch_urls = {}
    for target_lang in SUPPORTED_DASHBOARD_LANGS:
        params = current_params.copy()
        params["lang"] = target_lang
        switch_urls[target_lang] = build_path_with_query(request.path, params)
    nav = {
        "index": build_path_with_query(reverse("dashboard_index"), {"lang": lang}),
        "devices": build_path_with_query(reverse("dashboard_devices"), {"lang": lang}),
        "ops": build_path_with_query(reverse("dashboard_ops"), {"lang": lang}),
        "billing": build_path_with_query(reverse("dashboard_billing"), {"lang": lang}),
        "sales": build_path_with_query(reverse("dashboard_sales"), {"lang": lang}),
        "coupons": build_path_with_query(reverse("dashboard_coupons"), {"lang": lang}),
        "photos": build_path_with_query(reverse("dashboard_photos"), {"lang": lang}),
        "password_change": "/admin/password_change/",
    }
    return {
        "lang": lang,
        "currency_unit": currency_unit,
        "can_manage_billing": can_manage_billing(getattr(request, "user", None)),
        "text": text,
        "switch_urls": switch_urls,
        "nav": nav,
        "currency_action": reverse("dashboard_currency_unit"),
    }


def format_dashboard_amount(amount):
    try:
        return f"{int(amount or 0):,}"
    except Exception:
        return "0"
