# Generated by Django 5.2.11 on 2026-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apprelease',
            new_name='ota_apprele_platfor_0c3782_idx',
            old_name='ota_apprel_platfor_c44032_idx',
        ),
    ]
