# Generated by Django 5.2.11 on 2026-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_expires_292eae_idx',
            old_name='coupons_cou_expires_a_27b04a_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_cou_used_at_688e02_idx',
            old_name='coupons_cou_used_at_4e8a32_idx',
        ),
    ]
