# Generated by Django 5.2.11 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagehub', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadasset',
            new_name='storagehub__kind_b44661_idx',
            old_name='storagehub_u_kind_120607_idx',
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='object_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='storage_backend',
            field=models.CharField(default='local', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
