# Generated by Django 5.2.11 on 2026-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_alert_t_25538b_idx',
            old_name='alerts_aler_alert_t_e4180e_idx',
        ),
    ]
