# Generated by Django 5.2.11 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesession',
            name='files',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sharesession',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('uploading', 'Uploading'), ('finalized', 'Finalized')], default='init', max_length=16),
        ),
    ]
